### ISSUE TITLE
Add more fields to lucene index to increase result relevancy

### ISSUE THREAD

**Issue by smadha** [chrismattmann/lucene-geo-gazetteer#1]
Fields "feature class", "feature code", "population","country code", "admin1 code", "admin2 code" can help us defining granularity of our locations. Then we will use these fields to select most relevant location for a String.
1. "feature class" is a set of categories to bucket land masses in a broader class
2. "feature code" is a unique category to identify it as a city or state, country.
3. "population" have estimates of people living in that location
4. "country code" Country of location
5. "admin1 code" Can be State of location
6. "admin2 code" Can be county/district

For example Pasadena currently returns coordinates - 4.6964,-74.06446 which point to some Pasadena in Columbia while more known location could be Pasadena CA / Pasadena TX.

This link contain all codes: http://www.geonames.org/export/codes.html. 
This link contain schema and other deatils on data set http://download.geonames.org/export/dump/readme.txt

@chrismattmann Any more / Any less field you suggest?

**Comment by chrismattmann** [comment]
+1 makes sense to me. @smadha

**Comment by chrismattmann** [comment]
Solved in #4
