### ISSUE TITLE
Strange search results (esp. with lowercase names).

### ISSUE THREAD

**Issue by lopuhin** [chrismattmann/lucene-geo-gazetteer#17]
This is perhaps not a bug, but just want to share some examples of incorrect matching of locations:

```
$ ./src/main/bin/lucene-geo-gazetteer -s "russia" "china" "America"
[
{"russia" : [
"Republic of Belarus","28.0","53.0","BY","00",""
]},
{"china" : [
"Taiwan","121.0","24.0","TW","00",""
]},
{"America" : [
"South America","-57.65625","-14.60485","","",""
]}
]
```

Russia and China are recognized correctly if capitalized.

**Comment by smadha** [comment]
@lopuhin Thanks for pointing out. Few things below-

**##Why is this issue happening?**
  After getting result from indexed-geonames dataset we rank results on basis of our ranking algorithm and our ranking algorithm don't take case in consideration. 
  Checkout `resolvedName,extractedName` in below code-
  https://github.com/chrismattmann/lucene-geo-gazetteer/blob/master/src/main/java/edu/usc/ir/geo/gazetteer/GeoNameResolver.java#L294

 We will put it in our list of enhancement else If you like to submit a PR that would be awesome. 

**##Can you do something right now to get better results?**
Checkout `count` parameter and that might help you to select best results in your application code.

`-c,--count <number of results>        Number of best results to be returned for one location`

Maximum 8 results are supported for now.

```
$ lucene-geo-gazetteer -s russia china -c 2
[
{"russia" : [
"Republic of Belarus","28.0","53.0","BY","00","",
"Russian Federation","100.0","60.0","RU","00",""
]},
{"china" : [
"Taiwan","121.0","24.0","TW","00","",
"People’s Republic of China","105.0","35.0","CN","00",""
]}
]
```

**Comment by lopuhin** [comment]
Thanks for such a detailed response, @smadha

**Comment by smadha** [comment]
NP
@chrismattmann can we add this in release 0.3 ?

**Comment by chrismattmann** [comment]
yes let's add this in release 0.3 @smadha We'll get it addressed @lopuhin thanks for the interest in the project!

**Comment by chrismattmann** [comment]
I believe this issue was fixed
