### ISSUE TITLE
Use new fields in lucene index to calculate most relevant locations

### ISSUE THREAD

**Issue by smadha** [chrismattmann/lucene-geo-gazetteer#2]
One Possible implementation:
1. Define a sorting criteria for "feature class" and sort on it. This could be a possible order A P S T L H R V U
2. For each "feature class" define sorting criteria of "feature code" and sort on it.
3. Now sort it by population within same "feature class" and "feature code"
4. We need to modify our edit distance calculations because "China" is stored with "People's Republic of China" and so on. I propose below based on my observation on "alternatenames" field.
   - "alternatenames" contains a CSV of all pronunciations and synonyms for that location.
   - We split "alternatenames" and calculate edit distance with each of the variable on our sorted list 
     - if it's a exact match add this location to result list
     - if not store all edit distances and assign a weight to all "feature code" to prioritize bigger land masses and add those in the end of results.

@chrismattmann 
Can we take one extra parameter to define number of results that should be returned by lucene-geo-gazetteer?

**Comment by chrismattmann** [comment]
+1 @smadha

**Comment by chrismattmann** [comment]
note that we should then expose this in Tika so will need an associated JIRA there.

**Comment by chrismattmann** [comment]
done in #5
