### ISSUE TITLE
Return additional fields along with co-ordinates of location

### ISSUE THREAD

**Issue by smadha** [chrismattmann/lucene-geo-gazetteer#3]
@chrismattmann : How about returning country code, state, county along with co-ordinates? This information might make sense when we analyse this data in a context. It will allow us to group locations based on location's country, state and county.

[
{"Pasadena" : [
"Pasadena",
"-74.06446",
"4.6964",
"US",
"CA",
"37"
]}
]

**Comment by chrismattmann** [comment]
+1 @smadha

**Comment by chrismattmann** [comment]
@smadha shall we return these fields above?

**Comment by smadha** [comment]
Yeah sure, I will take this up next. Will raise a JIRA in tika for contextual analysis on these results.

**Comment by chrismattmann** [comment]
great thanks @smadha

**Comment by chrismattmann** [comment]
handled in #6
